# Generated by Django 6.0.5 on 2026-05-23 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EDICAO',
            fields=[
                ('id_edicao', models.AutoField(primary_key=True, serialize=False)),
                ('num_edicao', models.IntegerField(verbose_name='Número da Edição')),
                ('ano_edicao', models.IntegerField(verbose_name='Ano da Edição')),
            ],
        ),
        migrations.CreateModel(
            name='TIPO_QUESTAO',
            fields=[
                ('id_tipo_questao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_nome', models.CharField(verbose_name='Tipo de Questao')),
            ],
        ),
        migrations.CreateModel(
            name='FASE',
            fields=[
                ('id_fase', models.AutoField(primary_key=True, serialize=False)),
                ('num_fase', models.IntegerField(verbose_name='Número da Fase')),
                ('tipo_fase', models.IntegerField(verbose_name='Tipo da Fase')),
                ('id_edicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='SKYNET.edicao', verbose_name='Edição')),
            ],
        ),
        migrations.CreateModel(
            name='QUESTAO',
            fields=[
                ('id_questao', models.AutoField(primary_key=True, serialize=False)),
                ('num_questao', models.IntegerField(verbose_name='Número da Questão')),
                ('enunciado', models.TextField(verbose_name='Enunciado da Questão')),
                ('id_fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Questoes', to='SKYNET.fase', verbose_name='Fase')),
                ('id_tipo_questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Questoes', to='SKYNET.tipo_questao', verbose_name='Tipo De Questao')),
            ],
        ),
        migrations.CreateModel(
            name='ITEM',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('pontuacao', models.IntegerField(verbose_name='Pontuação do Item')),
                ('identificador', models.CharField(verbose_name='Identificador')),
                ('enunciado_item', models.TextField(verbose_name='Enunciado do Item')),
                ('id_questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tipo', to='SKYNET.questao', verbose_name='Questao')),
            ],
        ),
    ]
