# Generated by Django 6.0.5 on 2026-06-06 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKYNET', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='tipo_fase',
            field=models.CharField(max_length=100, verbose_name='Tipo da Fase'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id_questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tipos', to='SKYNET.questao', verbose_name='Questoes'),
        ),
    ]
