# Generated by Django 6.0.5 on 2026-07-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKYNET', '0002_alter_fase_tipo_fase_alter_item_id_questao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_questao',
            name='tipo_nome',
            field=models.CharField(max_length=100, verbose_name='Tipo de Questao'),
        ),
    ]
