# Generated by Django 6.0.5 on 2026-07-02 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SKYNET', '0003_alter_tipo_questao_tipo_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='enunciado_item',
            new_name='texto',
        ),
    ]
