# Generated by Django 6.0.5 on 2026-07-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKYNET', '0004_rename_enunciado_item_item_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANO_HISTORICO',
            fields=[
                ('id_ano', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField(verbose_name='Ano')),
            ],
        ),
        migrations.CreateModel(
            name='DOCUMENTO',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
                ('nome_documento', models.CharField(max_length=100, verbose_name='Nome do Documento')),
            ],
        ),
        migrations.CreateModel(
            name='PERIODO',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_nome', models.CharField(max_length=100, verbose_name='Nome do Periodo')),
                ('seculo', models.CharField(max_length=100, verbose_name='Seculo')),
            ],
        ),
        migrations.CreateModel(
            name='TAG',
            fields=[
                ('id_tag', models.AutoField(primary_key=True, serialize=False)),
                ('tag_nome', models.CharField(max_length=100, verbose_name='Nome da Tag')),
            ],
        ),
    ]
