# Generated by Django 6.0.5 on 2026-07-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKYNET', '0005_ano_historico_documento_periodo_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='documentos',
            field=models.ManyToManyField(related_name='questoes', to='SKYNET.documento'),
        ),
    ]
