# Generated by Django 6.0.5 on 2026-07-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKYNET', '0006_questao_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='periodos',
            field=models.ManyToManyField(related_name='questoes', to='SKYNET.periodo'),
        ),
    ]
