# Generated by Django 6.0.5 on 2026-07-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKYNET', '0007_questao_periodos'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='anos',
            field=models.ManyToManyField(related_name='questoes', to='SKYNET.ano_historico'),
        ),
        migrations.AddField(
            model_name='questao',
            name='tags',
            field=models.ManyToManyField(related_name='questoes', to='SKYNET.tag'),
        ),
    ]
